### ISSUE TITLE
Some dots disappear when we zoom out, others dont

### ISSUE THREAD

**Issue by AndyatFocallocal** [focallocal/fl-events#18]
would be god to keep them all so visitors can get an overview of the Whole Positive Social Action Movement, or all the events connected to an International Action Day

**Comment by mordka** [comment]
We cluster them intendedly into groups, to make them easily clickable when they are close to each other. I think it's not a bug.

**Comment by AndyatFocallocal** [comment]
sorry, i could have been clearer. when zooming out some individual dots independant from a cluster disappeared completely, others were still visible

**Comment by AndyatFocallocal** [comment]
not able to recreate. may have been solved, would suggest creating 10 - 20 dummy events, zooming all the way out and testing
