### ISSUE TITLE
text overlapping with a long address and title in list view

### ISSUE THREAD

**Issue by AndyatFocallocal** [focallocal/fl-events#23]

**Comment by mordka** [comment]
This is happening for small viewports so we can simply assign text or address a class that will hide on smaller devices

**Comment by AndyatFocallocal** [comment]
sure. my laptop screen is 12 inches for reference

**Comment by mordka** [comment]
Thank you @patison89 for fixing this

**Comment by AndyatFocallocal** [comment]
Awesome Patison, thank you :0)
